runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_0h7mqdq5:75d1ls60kagsujobej9ulvpuob@ds011462.mlab.com:11462/heroku_0h7mqdq5
  APP_ID: D6P9U6ClTipkBAuQwolXlc4DiypwVjK9oq9x9pjh
  MASTER_KEY: ODsesP0PIheUJJAFcONMIeFWfJBHdsse3ZAzCe8q
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  